//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Personal = new HashSet<Personal>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string EmpresaRut { get; set; }
        public string Tipo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> ComunaId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PaisId { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal { get; set; }
        public virtual Region Region { get; set; }
    }
}
